spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: amankumar.ak0012@gmail.com
    password: sbmt obhq gtje xwko
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true


